[origin]
description.default = "AOSC main repository (auto-redirect)"
description.zh_CN = "安同开源社区官方源（自动重定向）"
url = "https://repo.aosc.io/anthon/"

[origin4]
description.default = "AOSC main repository (auto-redirect) (IPv4 only)"
description.zh_CN = "安同开源社区官方源（自动重定向，仅 IPv4）"
url = "https://v4.repo.aosc.io/anthon/"

[origin6]
description.default = "AOSC main repository (auto-redirect) (IPv6 only)"
description.zh_CN = "安同开源社区官方源（自动重定向，仅 IPv6）"
url = "https://v6.repo.aosc.io/anthon/"

[repo-us]
description.default = "AOSC main repository (United States)"
description.zh_CN = "安同开源社区官方源（美国）"
url = "https://repo-us.aosc.io/anthon/"

[repo-hk]
description.default = "AOSC main repository (Aperture Science Limited, Hong Kong)"
description.zh_CN = "安同开源社区官方源（香港，由光圈网络托管）"
url = "https://repo-hk.aosc.io/anthon/"

[cernet]
description.default = "CERNET mirror"
description.zh_CN = "校园网联合镜像站"
url = "https://mirrors.cernet.edu.cn/anthon/"

[geekpie]
description.default = "GeekPie (ShanghaiTech University) Open Source Mirror"
description.zh_CN = "GeekPie（上海科技大学）开源镜像站"
url = "https://mirrors.shanghaitech.edu.cn/anthon/"

[lzuoss]
description.default = "LZUOSS Open Source Mirror"
description.zh_CN = "兰州大学开源社区镜像站"
url = "https://mirror.lzu.edu.cn/anthon/"

[nluug]
description.default = "Netherlands Local Unix User Group (NLUUG) OSS Mirror"
description.zh_CN = "荷兰本地 Unix 用户组 (NLUUG) 开源镜像站"
url = "https://ftp.nluug.nl/os/Linux/distr/anthon/"

[tsukuba]
description.default = "Tsukuba WIDE Public Mirror service"
description.zh_CN = "筑波 WIDE 公共镜像服务"
url = "https://ftp.tsukuba.wide.ad.jp/Linux/anthon/"

[tuna]
description.default = "Tsinghua Open Source Mirror (TUNA)"
description.zh_CN = "清华大学开源镜像站 (TUNA)"
url = "https://mirrors.tuna.tsinghua.edu.cn/anthon/"

[tuna4]
description.default = "Tsinghua Open Source Mirror (TUNA, IPv4 only)"
description.zh_CN = "清华大学开源镜像站（TUNA，仅 IPv4）"
url = "https://mirrors4.tuna.tsinghua.edu.cn/anthon/"

[tuna6]
description.default = "Tsinghua Open Source Mirror (TUNA, IPv6 only)"
description.zh_CN = "清华大学开源镜像站（TUNA，仅 IPv6）"
url = "https://mirrors6.tuna.tsinghua.edu.cn/anthon/"

[bfsu]
description.default = "Beijing Foreign Studies University OSS Mirror"
description.zh_CN = "北京外国语大学开源镜像站"
url = "https://mirrors.bfsu.edu.cn/anthon/"

[bfsu4]
description.default = "Beijing Foreign Studies University OSS Mirror (IPv4 only)"
description.zh_CN = "北京外国语大学开源镜像站（仅 IPv4）"
url = "https://mirrors4.bfsu.edu.cn/anthon/"

[bfsu6]
description.default = "Beijing Foreign Studies University OSS Mirror (IPv6 only)"
description.zh_CN = "北京外国语大学开源镜像站（仅 IPv6）"
url = "https://mirrors6.bfsu.edu.cn/anthon/"

[ustc]
description.default = "University of Science and Technology of China OSS Mirror"
description.zh_CN = "中国科学技术大学开源镜像站"
url = "https://mirrors.ustc.edu.cn/anthon/"

[ustc4]
description.default = "University of Science and Technology of China OSS Mirror (IPv4 only)"
description.zh_CN = "中国科学技术大学开源镜像站（仅 IPv4）"
url = "https://ipv4.mirrors.ustc.edu.cn/anthon/"

[ustc6]
description.default = "University of Science and Technology of China OSS Mirror (IPv6 only)"
description.zh_CN = "中国科学技术大学开源镜像站（仅 IPv6）"
url = "https://ipv6.mirrors.ustc.edu.cn/anthon/"

[staphlb]
description.default = "Load-balancing mirror offered by Staph. aureus (DO NOT use as the only mirror)"
description.zh_CN = "Staph. aureus 的自动负载均衡镜像（请勿作为唯一镜像使用）"
url = "https://s.aureus.icu/aosc/config/chance-1/"

[hit]
description.default = "Harbin Institute of Technology OSS Mirror"
description.zh_CN = "哈尔滨工业大学开源镜像站"
url = "https://mirrors.hit.edu.cn/anthon/"

[hit4]
description.default = "Harbin Institute of Technology OSS Mirror (IPv4 only)"
description.zh_CN = "哈尔滨工业大学开源镜像站（仅 IPv4）"
url = "https://mirrors4.hit.edu.cn/anthon/"

[hit6]
description.default = "Harbin Institute of Technology OSS Mirror (IPv6 only)"
description.zh_CN = "哈尔滨工业大学开源镜像站（仅 IPv6）"
url = "https://mirrors6.hit.edu.cn/anthon/"

[hexhu]
description.default = "Public Mirrors of Open-Source Software Projects by Hexhu with ❤"
description.zh_CN = "Hexhu 用❤发电的公共开源镜像站"
url = "https://mirror.hu.fo/anthon/"

[fastly]
description.default = "Fastly CDN Mirror"
description.zh_CN = "Fastly CDN 镜像"
url = "https://aosc-repo.freetls.fastly.net/anthon/"

[nju]
description.default = "Nanjing University OSS Mirror (NJU Mirror)"
description.zh_CN = "南京大学开源镜像站 (NJU Mirror)"
url = "https://mirror.nju.edu.cn/anthon/"

[xtom-estonia]
description.default = "xTom Open Source Software Mirror (Estonia)"
description.zh_CN = "xTom 开源镜像站（爱沙尼亚）"
url = "https://mirror.xtom.ee/anthon/"

[xtom-netherlands]
description.default = "xTom Open Source Software Mirror (Netherlands)"
description.zh_CN = "xTom 开源镜像站（荷兰）"
url = "https://mirror.xtom.nl/anthon/"

[aliyun]
description.default = "Alibaba Cloud Open Source Mirror"
description.zh_CN = "阿里云开源镜像站"
url = "https://mirrors.aliyun.com/anthon/"

[iscas]
description.default = "ISCAS Open Source Mirror"
description.zh_CN = "中科院软件所开源镜像站"
url = "https://mirror.iscas.ac.cn/anthon/"

[jlu]
description.default = "Jilin University Open Source Mirror"
description.zh_CN = "吉林大学开源镜像站"
url = "https://mirrors.jlu.edu.cn/anthon/"

[sjtug]
description.default = "SJTUG OSS Mirror (Shanghai Jiao Tong University)"
description.zh_CN = "上海交通大学 Linux 用户组软件源镜像服务"
url = "https://mirror.sjtu.edu.cn/anthon/"

[nit]
description.default = "Nanyang Institute of Technology Open Source Mirror"
description.zh_CN = "南阳理工学院开源镜像站"
url = "https://mirror.nyist.edu.cn/anthon/"

[sdu]
description.default = "SDU Mirrors (Shandong University)"
description.zh_CN = "山东大学开源镜像站"
url = "https://mirrors.sdu.edu.cn/anthon/"

[qlut]
description.default = "QLUT OSS Mirrors (Qilu University of Technology)"
description.zh_CN = "齐鲁工业大学开源软件镜像站"
url = "https://mirrors.qlu.edu.cn/anthon/"

[pku]
description.default = "PKU OSS Mirrors (Peking University)"
description.zh_CN = "北京大学开源镜像站"
url = "https://mirrors.pku.edu.cn/anthon/"

[tencent]
description.default = "Tencent Software Repository"
description.zh_CN = "腾讯软件源"
url = "https://mirrors.cloud.tencent.com/anthon/"

[sustech]
description.default = "SUSTech Open Source Mirrors"
description.zh_CN = "南方科技大学开源镜像站"
url = "https://mirrors.sustech.edu.cn/anthon/"

[sysu]
description.default = "SYSU OSS Mirrors (Sun Yat-sen University)"
description.zh_CN = "中山大学开源软件镜像站"
url = "https://mirror.sysu.edu.cn/anthon/"
